defmodule AiActors.ClaudeIntegration do
  @moduledoc """
  Integration layer for Claude Code to create new components in the system.

  This module provides a two-phase workflow:

  ## Phase 1: Design
  Claude Code creates:
  - High-level architecture document
  - Component interface specifications
  - Module boundaries and responsibilities
  - Data structures and state management approach
  - Integration points with existing system

  ## Phase 2: Implementation
  A specialized subagent consumes the design artifacts and:
  - Creates concrete implementations
  - Uses AiActor for intelligent components
  - Writes comprehensive tests
  - Adds documentation

  ## Usage

  From Claude Code, you would invoke:

      AiActors.ClaudeIntegration.create_component(
        name: "UserSessionManager",
        purpose: "Manage user sessions with automatic timeout and renewal",
        should_be_ai_actor: true,
        requirements: [
          "Track active user sessions",
          "Automatically timeout after 30 minutes of inactivity",
          "Renew sessions on activity",
          "Notify on session expiration"
        ]
      )

  This will:
  1. Generate a design document
  2. Invoke a subagent to implement
  3. Return paths to created files
  """

  require Logger

  @design_template """
  # Component Design: <%= name %>

  ## Purpose
  <%= purpose %>

  ## Requirements
  <%= for req <- requirements do %>
  - <%= req %>
  <% end %>

  ## Architecture

  ### Module Structure
  ```
  <%= module_path %>
  ├── Main Module: <%= module_name %>
  ├── State Structure: %{...}
  └── Public API: [...functions]
  ```

  ### State Management
  <%= if ai_actor do %>
  This component uses AiActor for intelligent state management.

  State schema:
  ```elixir
  %{
    # Define your state structure here
  }
  ```

  Development metadata:
  ```elixir
  %{
    purpose: "<%= purpose %>",
    design_decisions: [
      # Key architectural decisions
    ],
    dependencies: [],
    version: "0.1.0"
  }
  ```
  <% else %>
  Standard GenServer state management.
  <% end %>

  ### Public Interface

  ```elixir
  # Start the component
  @spec start_link(keyword()) :: {:ok, pid()} | {:error, term()}

  # Main API functions
  # TODO: Define based on requirements
  ```

  ### Internal Implementation

  #### Message Handlers
  - `handle_call` - Synchronous operations
  - `handle_cast` - Asynchronous operations
  - `handle_info` - Internal messages (timers, etc.)

  <%= if ai_actor do %>
  #### LLM Integration
  - Unknown messages escalated to LLM
  - Custom tools for domain-specific operations
  - Structured prompts for consistent responses
  <% end %>

  ## Integration Points

  ### Dependencies
  <%= for dep <- dependencies do %>
  - <%= dep %>
  <% end %>

  ### Supervised By
  - Application supervisor tree

  ## Testing Strategy

  ### Unit Tests
  - State transitions
  - Message handling
  - Error cases

  ### Integration Tests
  - Component interaction
  <%= if ai_actor do %>
  - LLM tool execution (mocked)
  <% end %>

  ## Implementation Notes

  <%= notes %>

  ---
  Generated by AiActors.ClaudeIntegration
  """

  @implementation_prompt """
  You are a specialized implementation agent. Your task is to create a concrete
  implementation of an Elixir component based on the design document provided.

  ## Design Document
  <%= design_doc %>

  ## Instructions

  1. Create the main module file at: <%= file_path %>

  2. If this is an AiActor (ai_actor: <%= ai_actor %>):
     - Use `use AiActors.AiActor`
     - Implement required callbacks: init/1, development_metadata/0
     - Define custom tools if needed via available_tools/0
     - Implement execute_tool/3 for custom tools
     - Add explicit handlers for known messages
     - Let unknown messages escalate to LLM

  3. If this is a standard GenServer:
     - Use `use GenServer`
     - Implement init/1 and message handlers
     - Create a clean, well-documented API

  4. Create comprehensive tests at: <%= test_path %>
     - Test all public API functions
     - Test state transitions
     - Test error conditions
     - For AiActors, test tool execution

  5. Follow Elixir best practices:
     - Clear module documentation with @moduledoc
     - Function documentation with @doc
     - Type specifications with @spec
     - Descriptive function and variable names

  ## Output Format

  Provide your implementation as a JSON object:

  ```json
  {
    "module_file": {
      "path": "lib/...",
      "content": "defmodule ... end"
    },
    "test_file": {
      "path": "test/...",
      "content": "defmodule ...Test do ... end"
    },
    "additional_files": [
      {
        "path": "...",
        "content": "...",
        "description": "..."
      }
    ],
    "implementation_notes": "Notes about the implementation..."
  }
  ```

  Begin implementation now.
  """

  @type component_spec :: %{
          name: String.t(),
          purpose: String.t(),
          requirements: list(String.t()),
          should_be_ai_actor: boolean(),
          dependencies: list(String.t()),
          notes: String.t()
        }

  @type design_result :: %{
          design_doc: String.t(),
          module_name: String.t(),
          file_path: String.t(),
          test_path: String.t()
        }

  @type implementation_result :: %{
          files_created: list(String.t()),
          module_name: String.t(),
          success: boolean(),
          notes: String.t()
        }

  @doc """
  Create a new component using the two-phase workflow.
  """
  @spec create_component(keyword()) :: {:ok, implementation_result()} | {:error, term()}
  def create_component(opts) do
    spec = %{
      name: Keyword.fetch!(opts, :name),
      purpose: Keyword.fetch!(opts, :purpose),
      requirements: Keyword.get(opts, :requirements, []),
      should_be_ai_actor: Keyword.get(opts, :should_be_ai_actor, false),
      dependencies: Keyword.get(opts, :dependencies, []),
      notes: Keyword.get(opts, :notes, "")
    }

    with {:ok, design} <- phase1_design(spec),
         {:ok, implementation} <- phase2_implementation(design, spec) do
      {:ok, implementation}
    end
  end

  @doc """
  Phase 1: Create high-level design and interface documentation.
  """
  @spec phase1_design(component_spec()) :: {:ok, design_result()} | {:error, term()}
  def phase1_design(spec) do
    Logger.info("Phase 1: Designing component #{spec.name}")

    module_name = "AiActors.Components.#{spec.name}"
    module_path = module_name_to_path(module_name)
    file_path = Path.join("lib", module_path <> ".ex")
    test_path = Path.join("test", module_path <> "_test.exs")

    design_doc =
      EEx.eval_string(@design_template,
        name: spec.name,
        purpose: spec.purpose,
        requirements: spec.requirements,
        module_name: module_name,
        module_path: module_path,
        ai_actor: spec.should_be_ai_actor,
        dependencies: spec.dependencies,
        notes: spec.notes
      )

    # Write design document
    design_path = Path.join("docs/designs", "#{Macro.underscore(spec.name)}_design.md")
    File.mkdir_p!(Path.dirname(design_path))
    File.write!(design_path, design_doc)

    Logger.info("Design document written to: #{design_path}")

    {:ok,
     %{
       design_doc: design_doc,
       module_name: module_name,
       file_path: file_path,
       test_path: test_path
     }}
  end

  @doc """
  Phase 2: Implement the component based on design.

  This phase can be delegated to a Claude Code subagent for actual implementation.
  """
  @spec phase2_implementation(design_result(), component_spec()) ::
          {:ok, implementation_result()} | {:error, term()}
  def phase2_implementation(design, spec) do
    Logger.info("Phase 2: Implementing component #{spec.name}")

    # Build the implementation prompt
    prompt =
      EEx.eval_string(@implementation_prompt,
        design_doc: design.design_doc,
        file_path: design.file_path,
        test_path: design.test_path,
        ai_actor: spec.should_be_ai_actor
      )

    Logger.info("""
    Implementation prompt prepared.

    In a real Claude Code integration, this would:
    1. Invoke a subagent with the prompt
    2. Parse the JSON response
    3. Write files to disk
    4. Return success/failure

    For now, returning the prompt as notes.
    """)

    {:ok,
     %{
       files_created: [],
       module_name: design.module_name,
       success: false,
       notes: """
       Implementation phase ready.

       To complete:
       1. Use Claude Code Task tool to spawn implementation agent
       2. Provide the design document and prompt
       3. Agent creates implementation and tests
       4. Files are written and validated

       Design document: docs/designs/#{Macro.underscore(spec.name)}_design.md
       Target module: #{design.file_path}
       Target tests: #{design.test_path}
       """
     }}
  end

  @doc """
  Helper to convert module name to file path.
  """
  def module_name_to_path(module_name) do
    module_name
    |> String.split(".")
    |> Enum.map(&Macro.underscore/1)
    |> Path.join()
  end

  @doc """
  Generate a skeleton implementation that can be refined.
  Useful for quick prototyping.
  """
  @spec generate_skeleton(component_spec()) :: String.t()
  def generate_skeleton(spec) do
    if spec.should_be_ai_actor do
      generate_ai_actor_skeleton(spec)
    else
      generate_genserver_skeleton(spec)
    end
  end

  defp generate_ai_actor_skeleton(spec) do
    module_name = "AiActors.Components.#{spec.name}"

    """
    defmodule #{module_name} do
      @moduledoc \"\"\"
      #{spec.purpose}

      ## Requirements
      #{Enum.map(spec.requirements, &"- #{&1}\n")}
      \"\"\"

      use AiActors.AiActor

      @impl AiActors.AiActor
      def init(args) do
        state = %{
          # TODO: Define initial state
        }
        {:ok, state}
      end

      @impl AiActors.AiActor
      def development_metadata do
        %{
          purpose: "#{spec.purpose}",
          design_decisions: [
            # TODO: Document key decisions
          ],
          dependencies: #{inspect(spec.dependencies)},
          created_at: DateTime.utc_now(),
          version: "0.1.0"
        }
      end

      # TODO: Add custom tools if needed
      # @impl AiActors.AiActor
      # def available_tools do
      #   AiActors.AiActor.default_tools() ++ [
      #     # Custom tools here
      #   ]
      # end

      # TODO: Implement message handlers
      # def handle_call(message, _from, state) do
      #   # Known messages handled here
      #   # Unknown messages will escalate to LLM
      #   :escalate_to_llm
      # end
    end
    """
  end

  defp generate_genserver_skeleton(spec) do
    module_name = "AiActors.Components.#{spec.name}"

    """
    defmodule #{module_name} do
      @moduledoc \"\"\"
      #{spec.purpose}

      ## Requirements
      #{Enum.map(spec.requirements, &"- #{&1}\n")}
      \"\"\"

      use GenServer

      # Client API

      def start_link(opts \\\\ []) do
        GenServer.start_link(__MODULE__, opts, name: __MODULE__)
      end

      # Server Callbacks

      @impl true
      def init(args) do
        state = %{
          # TODO: Define initial state
        }
        {:ok, state}
      end

      # TODO: Implement message handlers
      @impl true
      def handle_call(message, _from, state) do
        {:reply, :ok, state}
      end

      @impl true
      def handle_cast(message, state) do
        {:noreply, state}
      end

      @impl true
      def handle_info(message, state) do
        {:noreply, state}
      end
    end
    """
  end
end
